### ISSUE TITLE
DNS not supported in Windows ?

### ISSUE THREAD

**Issue by wimg** [earthquake/XFLTReaT#6]
When trying to use DNS on the client on Windows, I get an error telling me that's not supported.
Is there a specific reason why it wouldn't work ? Iodine and other tunneling tools seem to be able to do it.

**Comment by earthquake** [comment]
hi Wim!

Long story short, DNS packets are not capable to carry huge amount of data so the packets need to be fragmented. Fragmentation over a lossy protocol (DNS) is a hard problem and I had no time to solve it yet, so the operating system does it. On Linux it is easy to set the Maximum Segment Size (MSS) to a low value, I am not sure about Windows, so basically this is the reason.
Iodine work a very different way and because of that it is slow but reliable. It uses EDNS which is not an option in many cases (some servers do not support it), plus I guess it does its own fragmentation. 
Plus: the DNS module is a PoC in XFLTReaT.
